### ISSUE TITLE
Treat [MyClass class] specially

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#100]
This is a bit tricky - you've fixed greatly calling `-class` on instances to `.dynamicType`. But this returns the type of an instance. If you have the following code in ObjC:

```
Class cl = NSClassFromString(@"NSString");
BOOL isStringClass = (cl == [NSString class]);
```

This needs to be converted to:

```
let cl = NSClassFromString("NSString")
let isStringClass = (cl == NSString.self);
```

I.e. when the `-class` method is called on a class, it needs to be converted to `.self` instead of `.dynamicType`.

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.0.
