### ISSUE TITLE
Support @throw

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#103]
```
@throw [NSException exceptionWithName:@"XURTMPConnectionException" reason:@"Starting connection for the second time" userInfo:nil];
```

This can be converted to:

```
NSException(name: "XURTMPConnectionException", reason: "Starting connection for the second time", userInfo: nil).raise()
```

Note that you theoretically could use

```
throw NSException(name: "XURTMPConnectionException", reason: "Starting connection for the second time", userInfo: nil)
```

in Swift 2.0, but that is meant more for error handling with methods that in ObjC return a pointer to an `NSError` object and requires the method then be labeled as `throws`. I personally would prefer the first option.

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.0.
