### ISSUE TITLE
Use print/println instead of NSLog

### ISSUE THREAD

**Issue by drkameleon** [drkameleon/iswift#11]
To be implemented.

**Comment by drkameleon** [comment]
Note: `println` obsolete as of Swift 2.0

**Comment by drkameleon** [comment]
As of the upcoming 1.4:

- `NSLog` becomes `print` (Swift 2.0 compliant)
- All string format specifiers (as listed here: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html) are being replaced

------

**Example:**

```objective-c
int a = 2;

void main() {
    int a = 3;
    NSString* someStr = @"Hello world!";
    NSLog(@"This is an example: %d, Str: %@", a+2, [someStr uppercaseString]);
}
```

**Output:**

```swift
var a: Int = 2
func main() {
	var a: Int = 3
	var someStr: String = "Hello world!"
	print("This is an example: \(a+2), Str: \(someStr.uppercaseString())")

}
```

**Comment by bre7** [comment]
You could also use:

```swift
var a: Int = 2
func main() {
	var a: Int = 3
	var someStr: String = "Hello world!"
	print("This is an example: ", a+2, " Str: ", someStr.uppercaseString())

}
```

And avoid \()

**Comment by drkameleon** [comment]
> Or add a setting to use print with variadic parameters instead of a single string

That's exactly what I was thinking. A togglable option somewhere in the Preferences should be the best choice, in such cases. :)
