### ISSUE TITLE
Treat #if - #else - #endif otherwise than with an error

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#115]
Currently, once the parser gets to `#if`, it throws a syntax error. Probably just commenting the `#if - #else - #endif` lines would be fine and it can then needs to be fixed manually in the source code.

Just an idea - feel free to close this issue if you feel that it's out of the scope of the app to deal with pre-processor statements.

**Comment by drkameleon** [comment]
Well, that's an interesting issue as well.

Commenting them out WOULD be a solution.

The thing is, it's one of the parsing parts that have bothered me the most.

So, until I find a solution to that (even what you describe would be better than having it throw an error), I'll leave it open! :)

**Comment by charlieMonroe** [comment]
Actually, I found out, that in some cases, you can leave them as are:

```
#if DEBUG

#else

#endif
```

Is completely valid in Swift.

**Comment by drkameleon** [comment]
Well, the thing is ... at what extent does Swift support the C-preprocessor?

I, for instance, make EXTENSIVE use of C-style macros in my code. And it's one of the things I have the most trouble converting to swift...

**Comment by charlieMonroe** [comment]
It doesn't support anything else than the `DEBUG` option, really...

**Comment by drkameleon** [comment]
For now, the current situation with `#if` `#else` `#endif` is this:

the expression following `#if` must be in parentheses.

**Example:**

```objective-c
#if (DEBUG)

#else

#endif
```

**Output:**
```swift
if DEBUG {
} else {
}
```

---

I know it's an issue. But I still have to fix it so that it recognizes proper pre-processor syntax...

**Comment by drkameleon** [comment]
Closing for now (given that the only - mandatory - thing is the parentheses around the `#if` expression).

However, I'm putting `recheck` tag, for future reference. Your idea to simply comment them out is probably the best, since I doubt whether "translating" them will be of much use any way...
