### ISSUE TITLE
String interpolation vs C-style specifiers

### ISSUE THREAD

**Issue by drkameleon** [drkameleon/iswift#12]
**Example:**

    NSLog(@"This is a string: %@",str);

**Should be:**

    print("This is a string: \(str)");

**Comment by bre7** [comment]
`print("This is a string: ", str)` is arguably better (Possible as of beta 6)

**Comment by drkameleon** [comment]
Related with: https://github.com/drkameleon/iswift/issues/11

----

Fixed and closed. :-)
