### ISSUE TITLE
UIInterfaceOrientation Unexpected Identifier

### ISSUE THREAD

**Issue by bassrock** [drkameleon/iswift#127]
I have the following method in a ViewController:

```obj-c
-(void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation {
    [super didRotateFromInterfaceOrientation:fromInterfaceOrientation];
}
```

The converter does not like UIInterfaceOrientation as it says it is an unexpected identifier in this statement.

**Comment by drkameleon** [comment]
Fixed as of the upcoming 2.1.
