### ISSUE TITLE
iSwift fails to convert valid Objective-C code to Swift

### ISSUE THREAD

**Issue by ianhlavats** [drkameleon/iswift#128]
When attempting to convert this simple if statement it results in an error message:

if ([someObject someValue] != nil) {
 
}

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/3005952/11251661/99b0767e-8e32-11e5-96dc-77de67693e09.png)

Am I doing something wrong?

**Comment by drkameleon** [comment]
Ian, Hi!

What you entered **is** valid objective-c code. But is it a valid objective-c program?

What I'm saying is: would *that* compile in Xcode? Think about it.  ;-)

And the simple answer is: No, it wouldn't. It *is* valid code, but not a valid *program*. iSwift processes and "compiles" programs as a whole, not just a single statement (which wouldn't qualify as a valid program anyway).

if you did it like this (like a correct Objective-C program) though, it would work:

```objective-c
@implementation someClass
    - (void)someFunc {
           if ([someObject someValue] != nil) {

          }
    }
@end
```

Please let me know in case anything is unclear :)

**Comment by ianhlavats** [comment]
Thanks for the reply. I thought I was missing something obvious. ;) 

You may want to add support for converting code fragments if it's not too much trouble! It would save a lot of time for users like me.

Regards,
Ian

**Comment by drkameleon** [comment]
Well, Glad we sorted this one out! :)

As for your suggestion, to be honest, I've thought of it (to avoid mis-interpretations of what the app does, like this one), but given that it's build like a regular compiler-parser and based on the official Objective-C specifications (or at least trying to, as much as possible), this could make it a bit messy.

In any case, I'll add a "recheck" tag here - to revisit the issue at some later point, and not forget that it may still confuse people.

Thanks a lot for the input - keep it coming! ;-)

**Comment by drkameleon** [comment]
Issue moved here:

https://github.com/drkameleon/iswift/issues/164
