### ISSUE TITLE
Omit 'self' when not needed

### ISSUE THREAD

**Issue by drkameleon** [drkameleon/iswift#13]
**Example:**

    self.someMethod()

**Could be:**

    someMethod()

**Comment by drkameleon** [comment]
This seems to be rather tricky:

What if we want to differentiate between let's say property names and arguments?

    @property (strong) NSString* someVar

and

    - (void)doSth:(NSString*)someVar {
    
    }

**Comment by charlieMonroe** [comment]
If you end up implementing this, please, make it an option - in the code style I'm using, it's forbidden to use methods/properties on self without explicitly declaring `self.` since it's very error-prone...

**Comment by drkameleon** [comment]
Well, that's pretty much why I haven't implemented it. There are users that have asked for something like that - by I still believe it is error-prone as you say yourself... We'll see...
