### ISSUE TITLE
Tolerate semicolon at the end of ObjC method definitions

### ISSUE THREAD

**Issue by JanX2** [drkameleon/iswift#131]
These are a must for method declarations, but actually legal for method definitions as well:

    - (void)myMethod; // <- see here!
    {
          return;
    }

**Comment by drkameleon** [comment]
Hmm... Believe it or not, I had no idea.

Let me check a bit on this, and I will surely implement it.

**Comment by drkameleon** [comment]
Feature implemented as of the upcoming 2.1.
