### ISSUE TITLE
Unexpected :  #identifier ('NSMatchingFlags')

### ISSUE THREAD

**Issue by JanX2** [drkameleon/iswift#135]
When trying to convert the following:

		NSString *sourceString = nil;
		NSUInteger sourceStringLength = sourceString.length;
		NSRange sourceStringRange = NSMakeRange(0, sourceStringLength);
		
		NSMutableArray *URLs = [NSMutableArray array];
		
		NSError *error = NULL;
		NSDataDetector *detector = [NSDataDetector dataDetectorWithTypes:NSTextCheckingTypeLink
																   error:&error];
		[detector enumerateMatchesInString:sourceString
								   options:0
									 range:sourceStringRange
								usingBlock:^(NSTextCheckingResult *match, NSMatchingFlags flags, BOOL *stop){
									//NSRange matchRange = [match range];
									if ([match resultType] == NSTextCheckingTypeLink) {
										NSURL *url = [match URL];
										[URLs addObject:url];
									}
								}];

I get this error: “Unexpected :  #identifier ('NSMatchingFlags')”

A workaround is to 

		 typedef  NSUInteger NSMatchingFlags;

**Comment by drkameleon** [comment]
Well, it's the... usual suspect... The dread 'unrecognized type' error. :S

**Comment by drkameleon** [comment]
Issue (just) fixed as of the upcoming 2.2. :)
