### ISSUE TITLE
Convert NSDictionary to [NSObject : AnyObject]

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#142]
Xcode automatically converts pure non-generic `NSDictionary` usage to `[NSObject : AnyObject]`:

```
-(void)loadFromDictionary:(NSDictionary *)dict {
}
```

Currently is:

```
func loadFromDictionary(dict: Dictionary) {
}
```

Should be:

```
func loadFromDictionary(dict: [NSObject : AnyObject]) {
}
```

The same goes for `NSArray` -> `[AnyObject]`.

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.3.
