### ISSUE TITLE
Unexpected : #identifier ('launchOptions')

### ISSUE THREAD

**Issue by JanX2** [drkameleon/iswift#146]
NSWorkspaceLaunchOptions launchOptions;
	if (openLinksInBackground) {
		launchOptions = (NSWorkspaceLaunchWithoutActivation | NSWorkspaceLaunchDefault);
	} else {
		launchOptions = (NSWorkspaceLaunchDefault);
	}

I have to admit, that a good automatic translation isn’t easy in this case. This is what I came up with manually:

		var launchOptions: NSWorkspaceLaunchOptions = [.Default]
		if openLinksInBackground {
			launchOptions.insert(.WithoutActivation)
		}

**Comment by drkameleon** [comment]
Just an idea/hack: What if you set `@class NSWorkspaceLaunchOptions;` at the top?

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.3.
