### ISSUE TITLE
Support for int32_t

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#148]
Example:

```
[item setIndex:(int32_t)index];
```

Leads to an error unknown type `int32_t`. The same applies to `int8_t`, `int16_t`, `int64_t` and their unsigned counterparts: `uint32_t`, etc.

**Comment by charlieMonroe** [comment]
BTW the correct Swift types for those are `Int8`, `Int16`, ..., `UInt8`, ...

**Comment by drkameleon** [comment]
Support added as of the upcoming 2.3.
