### ISSUE TITLE
Pleaseee Support Third Party Frameworks!!

### ISSUE THREAD

**Issue by benjaminhallock** [drkameleon/iswift#152]
Can't convert most of my code because the compiler gets stuck on Classes it doesn't recognize. But this would be easy! 

[PFUser currentUser]  >>>> PFUser.currentUser()
@property PFObject *object >>>> var object:PFObject?
PFQuery *query = [PFQuery queryWithClassName:@"Class"]; >>>> let query = PFQuery(className: "Class")

Some of these the compiler can't assume. But it could at least try, and I will correct the bad ones.

**Comment by drkameleon** [comment]
Benjamin, I know what you mean...

Basically, it's not so much about "3rd Party Frameworks" as it is about  types no being recognized.

I can assure that it's one of my top priorities to solve - though definitely not an easy one.

In the meantime, you can try one of those "hacks":

- Add `@class XXXXX;` at the top of your code (where `XXXXX` is the class type not recognized
- Add a header "#import" at the top of your code (e.g. `#import "XXXXX.h"'`)
- Add any of the above 2 hacks to the Prefix Header under Preferences.

I know none of them is a ... "solution", but it's still sth. I'm currently working on it.

**Comment by benjaminhallock** [comment]
Thank you!! It works well. Here's my list of bugs 

underscore(_) should convert to self.
append() was accidentally added to a NSMutableArray instead of addObject
most of my booleens were in number form, so they didn't get converted.
UIBarButtonItem(barbuttonsystemitem:)  should have been camel cased

**Comment by drkameleon** [comment]
Benjamin, Hi!

To keep things organized, I'm closing this issue. Can you please elaborate on the list you mentioned and/or post them as separate issues?

(E.g. I'm not sure I understand what you mean about `append` at all - and I would be grateful if you could post some short code snippet about the rest of them too... ;-) )
