### ISSUE TITLE
Trailing comma in key-value list is legal

### ISSUE THREAD

**Issue by JanX2** [drkameleon/iswift#153]
The trailing comma in a key-value list for initializing a dictionary in modern ObjC is legal:

	NSDictionary *undoRootDict = @{
								   UndoFileVersionKey : @(kUndoFileCurrentVersionNumber),
								   UndoFileUsedSymbolicLinksKey : @(WantSymbolicLink),
								   UndoFileProcessedPairsKey : processedPairs,
								   };

iSwift only allows this construct when the trailing comma is deleted:

	NSDictionary *undoRootDict = @{
								   UndoFileVersionKey : @(kUndoFileCurrentVersionNumber),
								   UndoFileUsedSymbolicLinksKey : @(WantSymbolicLink),
								   UndoFileProcessedPairsKey : processedPairs // <- here!
								   };

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.3.
