### ISSUE TITLE
Ternary operator: ensure a space before the question mark

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#154]
Example:

```
-(NSString *)myMethodWithArg:(id)arg{
    return [self isReadyForArg:arg]? @"Value1" : @"Value2";
}
```

When this gets translated into this:

```
func myMethodWithArg(arg: AnyObject) -> String {
    return self.isReadyForArg(arg)? "Value1" : "Value2"
}
```

It generates an invalid code. Since the `?` is right behind the `)`, the question mark relates to the method call - the compiler then complains that there is no optional...

**Comment by drkameleon** [comment]
Hmm... I'm not sure I can reproduce this... We're talking about the latest 2.2, right?

![screen shot 2015-12-15 at 10 17 38 am](https://cloud.githubusercontent.com/assets/1265028/11806690/1e1c42c0-a315-11e5-9636-1c2b6c7eb09c.png)

**Comment by charlieMonroe** [comment]
Interestingly, I can't reproduce this now either. Please, ignore this.
