### ISSUE TITLE
init errors

### ISSUE THREAD

**Issue by aral** [drkameleon/iswift#156]
e.g.,

``` obj-c
@implementation CCHLinkTextView
- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        [self setUp];
    }
    return self;
}
@end
```

Gets translated as:

``` swift
class CCHLinkTextView {
    init(frame: CGRect) {
        self = super(frame: frame)
        if self {
            self.up = null
        }
        return self
    }
}
```

(Which, of course, doesn’t compile.)

Compare that to what Swiftify produces: 

``` swift
class CCHLinkTextView {
    convenience override init(frame: CGRect) {
        self.init(frame: frame)
        self.setUp()
    }
}
```

iSwift needs language & framework intelligence if it wants to be useful. Note, for example, how Swiftify knows it’s a convenience initialiser that’s being overriden.

**Comment by drkameleon** [comment]
Ref: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html

**Comment by drkameleon** [comment]
Aside from your remarks about Initializations (where you do have a point ofc), I'm opening separate issue for the `self.up = null` part, that is really... painful to look at, too.

**Comment by aral** [comment]
Cool, thanks :)

**Comment by drkameleon** [comment]
Working on the first part you mentioned (the first... results will be noticeable by 2.4 - 2.3 is the one coming right now, and will most likely be up in the next couple of hours).

As for the `self.up` part, I guess I missed it even myself... lol. Here's the solution: https://github.com/drkameleon/iswift/issues/157#issuecomment-165451562

Stay tuned - interesting stuff coming! ;-)
