### ISSUE TITLE
Minor casting bugs.

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#163]
The addition of support for casting is awesome - thanks! It has just three minor bugs I've come across:

```
enum XYZ;

-(void)doSomething:(id)sender{
    CGFloat x = (CGFloat)23.0;
    id someValue = (id)@"Something";
    XYZ enumValue = (XYZ)3;
}
```

Current output:

```
func doSomething(sender: AnyObject) {
	let x = (23.0 as? CGFloat) // Should be CGFloat(23.0)
	let someValue = AnyObject("Something") // Should be "Something" as? AnyObject
	let enumValue = (3 as? XYZ) // Should be XYZ(rawValue: 3), since XYZ is an enum.
}

```

**Comment by drkameleon** [comment]
Yep, good catch. I'm looking into it.

The only case I don't think I can cover is the case with the `enum`s. If it's a user-defined one, then perhaps, yes. But if it's not, it gets rather complicated (meaning I have to keep another - separate - list of all possible standard-library Cocoa enums... hm... )

**Comment by charlieMonroe** [comment]
I totally understand. In this case, I suggest:

- for user-defined enums, use the `rawValue:` initializer
- for other enums, since they cannot be detected, use the same casting as for a number type: `XYZ(3)` - Xcode will complain about the missing label, but will offer to insert the `rawValue:` label on its own, making the user-made fix fairly easy.

**Comment by drkameleon** [comment]
Progress as of the upcoming 2.4 (Basically it's working ok - except for the `enum`s which will require some further... work)

**Input:**

```objective-c
enum XYZ;
int index = (int)someValue;
CGFloat x = (CGFloat)23.0;
id someValue = (id)@"Something";
NSString* done = (NSString*)done;
NSTableView* myVar = (NSTableView *)[self superview];
XYZ enumValue = (XYZ)3;
```

**Output:**

```swift
var index: Int32 = Int32(someValue)
var x: CGFloat = CGFloat(23.0)
var someValue: AnyObject = ("Something" as? AnyObject)
var done: String = (done as? String)
var myVar: NSTableView = (self.superview() as? NSTableView)
var enumValue: XYZ = (3 as? XYZ)
```
