### ISSUE TITLE
NSNumber literal not recognized

### ISSUE THREAD

**Issue by kevnm67** [drkameleon/iswift#181]
iSwift doesn't recognize NSNumber literals and displays the error: "Unexpected: #constant('10')" for the following:

NSNumber *aNumber = @10;

**Comment by drkameleon** [comment]
Hmm... I'll have a look into it! ;-)

**Comment by kevnm67** [comment]
Thanks!

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 3.0.
