### ISSUE TITLE
Issue with @import keyword

### ISSUE THREAD

**Issue by blackjack75** [drkameleon/iswift#183]
See screenshot 

![atimport](https://cloud.githubusercontent.com/assets/473158/12823343/988a43b2-cb52-11e5-845c-ac752a10254f.png)

**Comment by drkameleon** [comment]
The `@import` keyword is not supported yet (to be honest, I had to look it up to make sure it exists...), but I'm putting it in my to-do list for the upcoming update. :)

**Comment by drkameleon** [comment]
Fixed as of the upcoming 3.0.
