### ISSUE TITLE
I cannot seem to get beyond the first few lines of code

### ISSUE THREAD

**Issue by jsutdolph** [drkameleon/iswift#191]
``` objective-c
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class SSDragItem;

@protocol SSDragItemSource
    -(bool) hit:(UIGestureRecognizer *)panReco;
    -(SSDragItem *)pan:(UIGestureRecognizer*)gr;
@end
```

It finds an error on the @class line, and if I remove that it finds an error on the @protocol line. What's the problem?

**Comment by drkameleon** [comment]
Hmm... I really have no idea. I experimented a bit and it seems like you're right. I'm looking into it!

**Comment by drkameleon** [comment]
Better `@protocol` support and implementation in the upcoming 3.0.

Your example would now work fine (by also changing `bool` to `BOOL`).

**Source**

```objective-c
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class SSDragItem;

@protocol SSDragItemSource
    -(BOOL) hit:(UIGestureRecognizer *)panReco;
    -(SSDragItem *)pan:(UIGestureRecognizer*)gr;
@end
```

**Output**
```swift
import Foundation
import UIKit

protocol SSDragItemSource : class {
	func hit(panReco: UIGestureRecognizer) -> Bool
	func pan(gr: UIGestureRecognizer) -> SSDragItem
}
```

**Comment by multinerd** [comment]
Unexpected: @protocol

    @protocol KRLCollectionViewDelegateGridLayout <NSObject>
    @end
