### ISSUE TITLE
I just purchased the software and now it's not converting anything like the trial was.

### ISSUE THREAD

**Issue by 00Spitfire** [drkameleon/iswift#196]
The app just does not seem to run since I put in my license.

**Comment by drkameleon** [comment]
Can you please clarify a bit what you mean by "does not seem to run"? 
Does it not start at all? Or is it something to do with the code conversion?

**Comment by drkameleon** [comment]
Could you please contact me via email (at info@insili.co.uk) so that we take it from there?
