### ISSUE TITLE
Issue Converting Nullability Annotations

### ISSUE THREAD

**Issue by KingOfNinjas** [drkameleon/iswift#198]
This issue addresses the problem which occurs in the task of converting Objective-C code to Swift within a project where the use of Nullability Annotations (`_Nonnull` and `_Nullable`) are applied.
**E.g.:**
`NSString *_Nullable message;` should be converted to `var message: String?`

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 3.0.

**Example:**
```objective-c
@implementation aClass

- (void)someFunc {
    NSString *_Nonnull message;
}

@end
```

**Output:**
```swift
class aClass {

	func someFunc() {
		var message: String?
	}
	
}
```
