### ISSUE TITLE
#warnings not supported

### ISSUE THREAD

**Issue by JamaicanRumCream** [drkameleon/iswift#199]
Using #warning Blah blah blah
is not supported but should be turned into comments.
Keeps failing on whatever text is after 'warning' word

**Comment by drkameleon** [comment]
Noted. Probably - since i'm in the middle of iSwift's... comeback - the fix will be included in the upcoming release.

Stay tuned!

**Comment by drkameleon** [comment]
Fixed as of the upcoming 3.0 ;-)
