### ISSUE TITLE
In den Youtube-Video

### ISSUE THREAD

**Issue by dasdom** [drkameleon/iswift#2]
`i++` gets translated in `i--`.

**Comment by drkameleon** [comment]
Well, this is one of those super-obvious types. Which I missed.

Good job spotting it and thanks for letting me know. (The fix will be included in the very next release).

**Comment by drkameleon** [comment]
Related: https://github.com/drkameleon/iswift/issues/14

---

Closed as fixed (in the upcoming 1.3).
