### ISSUE TITLE
Floating-point constant not being recognized

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#20]
I believe that the CGRectMake is having issues when the values are 0.0f. This needs to be confirmed as I'm not 100%. 

Steps to reproduce.
1.) Copy the following code into iSwift
   AirportPlatesTableView.contentInset = UIEdgeInsetsZero;
    AirportPlatesTableView.tableHeaderView = [[UIView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, self.AirportPlatesTableView.bounds.size.width, 0.01f)];

2.) Review the error provided. 

Expected results:
I believe they should be as followed, however I'm no expert in Swift.
AirportPlatesTableView.contentInset = UIEdgeInsetsZero
AirportPlatesTableView.tableHeaderView = UIView(frame: CGRectMake(0.0, 0.0, self.AirportPlatesTableView.bounds.size.width, 0.01))

Actual Results:
Errors stipulating that "Unexpected : #constant ('.0f)'"

**Comment by drkameleon** [comment]
Well, I confirm it. It has nothing to do with `CGRectMake` whatsoever.

It's similar with this one: https://github.com/drkameleon/iswift/issues/19#issuecomment-135147875

And it has to do with the floating-point constant. Let's see...

**Comment by jermowatson** [comment]
Yeah, I wasn’t sure sorry. I’m not sure what constitutes as a bug and one that doesn’t i.e. its my fault. 

Also, I tried to remove the floating point to help as well. But didn’t get a chance to see if that works as I got pulled into something else. 

Regards,

Jeremy

**Comment by drkameleon** [comment]
Well, the issue has just been confirmed - as you can judge by my changing your post's title. And fixed. :)

So... you'll find the fix included in the very next release - as usual.

**Comment by jermowatson** [comment]
Rocking man. If I find things would you like me to continue putting them into the bug reports? Even though it may be me?

Regards,
Jeremy

**Comment by drkameleon** [comment]
Of course! :)

P.S. And it'll most likely *not* be... "just you". ;-)

**Comment by jermowatson** [comment]
Yeah I'm green with iOS but I sorta know what I'm doing.

**Comment by drkameleon** [comment]
> Yeah I'm green with iOS but I sorta know what I'm doing.

Rest assured that when it comes to iOS - specifically iOS - I'm as much of a beginner as it gets. Being a programmer for the past 20+ years (no, I'm not thaaat old lol), I still cannot find a real meaning in... programming something that is supposed to make calls and fits in my palm. lol

**Comment by jermowatson** [comment]
Hahahaha. Well said. Well I'll do my best to help out. As I see what your
doing will add value to anyone learning. I.e me. Eventually everyone will
be using swift I would imagine.
