### ISSUE TITLE
IBOutlet reference not being properly converted

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#23]
Steps to reproduce:
1.) Open up iSwift
2.) The following set of code.
@property (strong, nonatomic) IBOutlet UITableView *AirportPlatesTableView;

Expected results:
@IBOutlet var AirportPlatesTableView: UITableView?

Actual results:
var airportICAOCode: IBOutlet?

Again unsure if this is something we the programmer needs to adjust after the conversion or of its something that is an error. Your call.

**Comment by drkameleon** [comment]
Yes, you're right. Good spot. (That's why feedback is great. I mean, I'm spotting things myself, write down most of them, then at some point forget about something and... it's gone...)

I'll look into it and I'll let you know. ;-)

**Comment by jermowatson** [comment]
No problem. 

I worked out that most of them i.e. IBOutlet, UITable, UILabel etc seem to follow the same issue. :-)

**Comment by drkameleon** [comment]
Well, basically it's whenever `IBOutlet` is used, nope?

----

I'm currently *very* close to getting it fixed.

**Comment by jermowatson** [comment]
Yeah I think so. From what I can see. I haven’t tried with others yet. Also I recommend your solution to someone I had a meeting with today :-P.

**Comment by drkameleon** [comment]
Related Issue (just noticed it, and opened it myself - thought it's 5 mins away from being... closed :-) )

https://github.com/drkameleon/iswift/issues/26

**Comment by drkameleon** [comment]
Fixed as of the upcoming 1.4. ;-)

**Comment by jermowatson** [comment]
Excellent.

**Comment by drkameleon** [comment]
> Excellent.

:-)
