### ISSUE TITLE
#define preprocessor statements not being recognized

### ISSUE THREAD

**Issue by drkameleon** [drkameleon/iswift#25]
#define statements - since they're rather challenging to be converted should be copied (and commented out) to the output.

**Example:**

```objective-c
#define SOME_MACRO(X) DO_SOMETHING_WITH(X)
```

**Output:**

```swift
// #define SOME_MACRO(X) DO_SOMETHING_WITH(X)
```

**Comment by drkameleon** [comment]
Fixed as of the upcoming 1.4.

**Comment by bre7** [comment]
Or convert it to a global function ?

**Output:**
```swift
func SOME_MACRO(X) {
    DO_SOMETHING_WITH(X)
}
```

**Comment by drkameleon** [comment]
> Or convert it to a global function ?

This is something I've thought of too. Let me see...
