### ISSUE TITLE
Unrecognized identifier

### ISSUE THREAD

**Issue by bre7** [drkameleon/iswift#32]
`UIStatusBarStyle` is the cause of the error. If I change it for NSString, it works.

```objectivec
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@implementation Test

+ (UIStatusBarStyle)statusBarStyleForColor:(UIColor *)backgroundColor {
    return UIStatusBarStyleDefault;
}

@end
```

Similar to #27 but for UIKit enums ?

**Comment by drkameleon** [comment]
Hmm... Well. It's not related to the Enums issue.

It's just that: "Unrecognized identifier".

Currently, the app works by telling the difference between Types and Identifiers (anything which is not a reserved word or a "Type"). The list of recognized types is rather long (right now, > 2k), but this is an example that I can still... miss some things: `UIStatusBarStyle` for instance.

I'll get it fixed asap. ;-)

**Comment by drkameleon** [comment]
Closed as related to: https://github.com/drkameleon/iswift/issues/42
