### ISSUE TITLE
Need to follow #import for identifiers

### ISSUE THREAD

**Issue by kjk** [drkameleon/iswift#34]
Trying to convert https://github.com/gnachman/iTerm2/blob/master/sources/AlertTrigger.m, fails on:

```
#import "PTYSession.h"

...

- (BOOL)performActionWithCapturedStrings:(NSString *const *)capturedStrings
                          capturedRanges:(const NSRange *)capturedRanges
                            captureCount:(NSInteger)captureCount
                               inSession:(PTYSession *)aSession
                                onString:(iTermStringLine *)stringLine
                    atAbsoluteLineNumber:(long long)lineNumber
                                    stop:(BOOL *)stop {
    if (disabled_) {
        return YES;
    }
```
with: "unexpected: #identifier ('PTYSession')".

Based on your comment in another issue, list of identifiers is hard-coded and obviously will never include `PTYSession`, which is defined in "PTYSession.h". Without being able to resolve this generically by following #import statements, it's not going to be practical to convert real-life projects.

**Comment by drkameleon** [comment]
Perfect point. And ues, the only way to "resolve" this would be to keep a separate "active" symbol list, meaning:

- classes imported
- classes with a visible `@interface`

in a few words, I've already worked on that, and it'll be fixed very soon. ;-)

**Comment by drkameleon** [comment]
Closed as related to: https://github.com/drkameleon/iswift/issues/42
