### ISSUE TITLE
Feature Request: Placeholder template for @implemation

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#38]
Is it possible to have the @implementation & @interface as a greyed out place holder in the left side of the objective c panel? The purpose is just to illustrate the minimums of what is needed. Sounds way basic but nice to illustrate.

**Comment by drkameleon** [comment]
Hmm... I've thought of that too.

Since the app currently recognizes (or tries to :) ) "valid" Objective-C apps - and not just anything - I can tell that at times, I even forget myself.

So, you do have a point - a generic placeholder wouldn't be a bad idea at all.

Noted. :)

**Comment by jermowatson** [comment]
Rad.

**Comment by drkameleon** [comment]
Implemented as of the upcoming 1.5.

**Comment by jermowatson** [comment]
Whoo hoo! 

I will eagerly wait for 1.5….I haven’t really gone any further for other reasons but will start looking at everything again once 1.5 is released. That way hopefully I’m not double up’ing on bugs i.e. known ones.

**Comment by drkameleon** [comment]
> I will eagerly wait for 1.5….

No reason to wait. It's already out :)

**Comment by jermowatson** [comment]
What?! Hahaha I didn’t check its still really early here hahaha I’m on it!

**Comment by drkameleon** [comment]
> What?! Hahaha I didn’t check its still really early here hahaha I’m on it!

;-)

**Comment by drkameleon** [comment]
Code block conversion is coming... so... 

Related: https://github.com/drkameleon/iswift/issues/164
