### ISSUE TITLE
Push Views: to new storyboard view. 

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#39]
When trying to push to a new starboard instance i.e. new view an error comes to the = symbol suggesting that it requires additional syntax. This error my be similar to the other error I raised in relation to Global Objects. However, that is an assumption. 

Using the following Code:
PlatesViewController *detail = [self.storyboard instantiateViewControllerWithIdentifier:@"PlatesView"]

Expected Results:
 var detail: PlatesViewController = self.storyboard.instantiateViewControllerWithIdentifier("PlatesView")
(double check the syntax on this one as I'm not 100%)

Actual Results:
Error preventing to further convert.

**Comment by drkameleon** [comment]
Hmmm... again same as: https://github.com/drkameleon/iswift/issues/37

`PlatesViewController` being the culprit.

However, as I told you, I'm working on it: basically if it can see your "imports" (and `PlatesViewController` is there, then it'll be registered as a valid type - that's the idea)

**Comment by drkameleon** [comment]
Closed as related to: https://github.com/drkameleon/iswift/issues/42

**Comment by jermowatson** [comment]
Sorry. I couldn’t remember if I raised it or not. My Bad.
