### ISSUE TITLE
Unable to convert file with NSString

### ISSUE THREAD

**Issue by bre7** [drkameleon/iswift#4]
Example code:

```Objective-c
//
//  NSString+SomethingNew.h
//

#import <Foundation/Foundation.h>

@interface NSString (SomethingNew)

-(BOOL)newMethodExample;

@end

//
//  NSString+SomethingNew.m
//

#import "NSString+SomethingNew.h"

@implementation NSString (SomethingNew)

#pragma mark - Public Getter Methods

- (BOOL)newMethodExample {
    return true;
}

@end

```

Error:
> Unexpected #type : ('NSString')

**Comment by drkameleon** [comment]
Actually the "issue" is not the `NSString` itself. There are 2-3 issues, which are to be resolved very soon, and that all have to do with some details not being recognized. Namely:

- Class extensions (the interface declaration `NSString (SomethingNew)` and the implementation `NSString (SomethingNew)`)
- `#pragma` statements

I'm telling you that I'll do my best to have them both implemented until the next release. But - until then - you can see what I mean by commenting out the `#pragma` statement and setting `NSString (SomethingNew)` to let's say `NSString_SomethingNew`.

Like:

```objective-c

//
//  NSString+SomethingNew.h
//

#import <Foundation/Foundation.h>

@interface NSString_SomethingNew

-(BOOL)newMethodExample;

@end

//
//  NSString+SomethingNew.m
//

#import "NSString_SomethingNew.h"

@implementation NSString_SomethingNew

//#pragma mark - Public Getter Methods

- (BOOL)newMethodExample {
    return true;
}

@end

```

**Comment by drkameleon** [comment]
Related: https://github.com/drkameleon/iswift/issues/8
