### ISSUE TITLE
CGRectMake: Omit 0.0f attribute or change & Content Inset syntax

### ISSUE THREAD

**Issue by jermowatson** [drkameleon/iswift#41]
I may have already raised this one. I can't remember sorry. When converting a CGRectMake it doesn't like the 0.0f attribute and fails. Also Content Inset Syntax I believe requires a "!" when referencing .contentInset. This particular is true when referencing a UITableView. I put these two issues together as it was in the same code block.

Try code:
(Objective C)
self.automaticallyAdjustsScrollViewInsets = NO;
AirportPlatesTableView.contentInset = UIEdgeInsetsZero;
AirportPlatesTableView.tableHeaderView = [[UIView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, self.AirportPlatesTableView.bounds.size.width, 0.01f)];

Expected Results:
(Swift)
self.automaticallyAdjustsScrollViewInsets = false
AirportPlatesTableView!.contentInset = UIEdgeInsetsZero
AirportPlatesTableView!.tableHeaderView = UIView(frame:CGRectMake(0.0,0.0,self.AirportPlatesTableView!.bounds.size.width,0.01f))

(double check Swift syntax as I'm not 100%)

Actual Results:
(Swift)
self.automaticallyAdjustsScrollViewInsets = false
AirportPlatesTableView.contentInset = UIEdgeInsetsZero
AirportPlatesTableView.tableHeaderView = UIView(frame:CGRectMake(0.0f,0.0f,self.AirportPlatesTableView.bounds.size.width,0.01f))

**Comment by drkameleon** [comment]
> When converting a CGRectMake it doesn't like the 0.0f attribute and fails.

Hmm... So, it actually stuck there again? I'll look into it... Seems weird...

> Also Content Inset Syntax I believe requires a "!" when referencing .contentInset. This particular is true when referencing a UITableView.

Now, regarding this one - since I'm most definitely not an iOS guru - I'll have to look into it. Any input from anyone is more than welcome. (Though to be honest, translating this type of things can end up being very tricky... I mean how can all these conversions be recognized? Or - technically speaking: What's the pattern?)

**Comment by jermowatson** [comment]
Yeah, 

Your call on this one. I wasn’t sure if you wanted to fix that second part to that. i.e. the “!” Being predominantly iOS I’m unsure how it would translate to other aspects. Again your call, unless someone else has a different perspective. 

> Hmm... So, it actually stuck there again? I'll look into it... Seems weird...
> 

Yep, I can manually fix it but I’m sure you had fixed that.

**Comment by drkameleon** [comment]
> Yep, I can manually fix it but I’m sure you had fixed that.

How can you "manually" fix it? By deleting the `f` part or the whole decimals part?

**Comment by jermowatson** [comment]
Yeah,

Basically taking out the f and adding in the ! where appropriate. Again, I’m not an expert at Swift so I’m unsure if the syntax will even work when you compile it in run time as I haven’t even gotten to the level of hooking bit up to the UI. So time will tell.

**Comment by drkameleon** [comment]
Aha... I believe I initially misunderstood what you were talking about. (I thought you were saying about `0.0f` not being converted).

Now that I tried it myself, I can see what you mean. Now, if you ask *me*, as weird as that may seem, I'm not a Swift expert either. (learning and going on as pretty much everyone else with Swift, so no worries).

But this `0.0f`(with a `f` and everything) seems too C-ish, and I doubt whether it's valid swift. Time to re-open the Swift 2.0 manual... I'll look into it! :)

**Comment by jermowatson** [comment]
No problem. I think swift doesn't require the .f but looks like it's review time. Incidentally what version are you basing the swift code from? 1.5 or 2.0

**Comment by drkameleon** [comment]
Well, I started with 1.2 (when I started writing it), but decided to move to 2.0. It's coming, so no reason to be behind. :)

To be precise: Apple Swift version 2.0 (swiftlang-700.0.57.3 clang-700.0.72)

----

I constantly check every output, so that it makes sense.

**Comment by jermowatson** [comment]
Oh okay coolz

**Comment by drkameleon** [comment]
To be honest, I was thinking of adding some option to choose between 1.2 and 2.0. But what's the point in that? Before we even realize, 1.2 will be a thing of the past.

**Comment by jermowatson** [comment]
Yeah exactly. Best to just iterate slowly all the time.

**Comment by drkameleon** [comment]
"0.0f" being formatted as "0.0" as of the upcoming 1.5.

So, I close this.

Now, regarding the "adding in the ! where appropriate" part, I'll keep it in my to-do list, though as an optimization, to be implemented once all syntax/core things are all sorted out. :)

**Comment by jermowatson** [comment]
No problem. I’ll make a note to change in the code where appropriate. Do you have a location to put known issues? Even though its not really an issue but a syntax change…if you know what I mean.
