### ISSUE TITLE
Parenthesis not respected

### ISSUE THREAD

**Issue by lrtitze** [drkameleon/iswift#43]
CGFloat u = (pointX - lineStartPointX) * (lineEndPointX - lineStartPointX);
  becomes:
let u: CGFloat = pointX-lineStartPointX*lineEndPointX-lineStartPointX

Perhaps you could simply strip the trailing semicolon and leave the rest intact? (although I assume it's FAR more complicated than that and involves parse trees etcetera)

**Comment by drkameleon** [comment]
> ... and involves parse trees etc....

Yes. :)

**Comment by lrtitze** [comment]
:-)

**Comment by drkameleon** [comment]
> Well, have fun. :-)

Well, I most definitely do have fun. Given than compilers/interpreters and all that (geeky?) stuff has been my lifelong passion, this converter must be one of the most enjoyable projects I've played with! :)

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 1.5.
