### ISSUE TITLE
On lines with return, extraneous ; is left

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#65]
Example:

```
@interface MyClass
@end

@implementation MyClass
-(BOOL)isItTrue{
    return NO;
}
@end
```

Result:

```
class MyClass {

	func isItTrue() -> Bool {
		return false;
	
	}
	
}
```

There is also an extra newline after the return statement.

**Comment by drkameleon** [comment]
Good catch. And a rather simple fix.

So... Fixed (already) for the upcoming 1.9. ;-)

----

As for `There is also an extra newline after the return statement.`, I know what you mean. And for keeping things a bit more organized I'm moving that to a separate issue.
