### ISSUE TITLE
Class extensions not recognized

### ISSUE THREAD

**Issue by drkameleon** [drkameleon/iswift#7]
Currently Class extensions' definition is not being recognized, e.g.

    @interface UIColor (MyExtension)

or

    @implementation UIColor (MyExtension)

-----

A quick fix is to simply change the syntax like "UIColor_MyExtension" - but it's in my to-fix list.

**Comment by drkameleon** [comment]
Fixed as of the upcoming 1.3.

**Comment by bre7** [comment]
Nice. Thanks for that ;)
