### ISSUE TITLE
Convert the -class method to .dynamicType

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#70]
Sorry about all these issues :)

`[[self class] doSomething]` becomes `self.class().doSomething()`, but should become `self.dynamicType.doSomething()`

**Comment by drkameleon** [comment]
Hmm... I guess I'm not that... fluent in Swift. I'll have a look into it!

**Comment by charlieMonroe** [comment]
See http://stackoverflow.com/a/24102130/1800936

**Comment by drkameleon** [comment]
> See http://stackoverflow.com/a/24102130/1800936

Yup, indeed. :)

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 1.9.

----

**Example:**

```objective-c
[[X class] doSomething];
```

**Output:**

```swift
X.dynamicType.doSomething()
```
