### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#79]
On El Capitain, select iSwift -> Check For Update shows an error. The issue here is that the update feed URL uses plain HTTP, which is blocked by default by El Capitain - see https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

You need to either use HTTPS, or declare it as an exception in Info.plist.

**Comment by drkameleon** [comment]
Yep, 100% spot on.

- **The bad news:** this thing seems to have affected LOTS of apps (and many of my own).
- **The good news:** I've already resolved it (at least for iSwift). So it's coming in the update I'll release tomorrow - 1.9. :)

---

Have a look here: https://github.com/drkameleon/iswift/issues/72
