### ISSUE TITLE
Option to use override as default

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#80]
This is probably a very specific usecase, but this option would help me a lot.

I have a project with one root class and then about 1000 subclasses of this class which usually just override existing methods of the root class. Which means that I need to manually enter `override` in front of each method declaration - this is very tedious and such an option would help me a lot.

This could become a more generic option:

**Default method modifiers:**
[ ] public
[ ] private
[ ] internal
[ ] override

**Comment by drkameleon** [comment]
Hmm... This sounds too personalized I guess. However, giving the options to add some default modifiers methods could possibly be done (again in the Preferences).

I'll think about it!

---

Anyone else wanting to share some ideas on the matter is more than welcome!

**Comment by drkameleon** [comment]
Feature implemented as of the upcoming 2.1. :)

---

**Example:**

![screen shot 2015-12-01 at 3 56 40 pm](https://cloud.githubusercontent.com/assets/1265028/11504178/51bf42f2-9844-11e5-9b2f-f40146ca10cc.png)
