### ISSUE TITLE
Option to default methods without arguments to properties

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#81]
Example:

```
[[self URL] absoluteString];
```

will become:

```
self.URL().absoluteString();
```

which is wrong.

99% of the time, leaving out the parenthesis is correct. The 1% time is when it's actually a method.

**Comment by drkameleon** [comment]
This is something that I've been thinking. But I guess you might be right: most "methods" without arguments are usually properties and not methods. So, your idea might work.

For now, I'll implement it the way you suggest (as an "option") and let's see how this goes...

**Comment by drkameleon** [comment]
Implemented as of the upcoming 1.9.
