### ISSUE TITLE
Prefix Header File

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#88]
Just a thought:

The usual way I work with iSwift is that I copy over content of the .m file. Usually, it works just fine, but sometimes it doesn't recognize some of the symbols. For example, classes within the same project.

I solve this manually by typing this to the top of the text area in iSwift:

```
@class MyClass1, MyClass2;
```

The same for enums:

```
enum MyEnum;
```

While this works just fine and iSwift is then able to parse and convert the source code, it is kind of tedious and needs to be repeated each launch.

The solution for this would be to allow a prefix header file - just like Xcode used to. It is discouraged now to use a prefix header file, but generally it is a header file that is imported to every single source file within the Xcode project. It is mostly for importing large frameworks which get pre-indexed and it helps with compilation times.

Many developers (including me), kind of abuse this file to include classes/header files that are used in ~70% of the source files.

If iSwift allowed such a file that would be automatically imported, it would help a lot. Not sure if this makes sense. Let me know if you have any questions.

**Comment by drkameleon** [comment]
Hm... It does make sense. (The thing is I've already thought of something like that. However, since I'm experimenting - *only experimenting for now* - with some more... ambitious options (e.g. Xcode plugin, folder conversion, etc), I've postponed it a bit).

How would you expect it to work? E.g. an option (with a specific Prefix Header path) @ Preferences?

**Comment by charlieMonroe** [comment]
Generally you'd either select a file, or just entered some text in Preferences that would get inserted at the very top of the input source.

**Comment by drkameleon** [comment]
> Generally you'd either select a file, or just entered some text in Preferences that would get inserted at the very top of the input source.

Do you think it would make sense to make it a session-specific option (like: add a prefix header for the current "session" only, and once you close the app, it's gone) or have it as something more... universal (e.g. in the Preferences)?

**Comment by charlieMonroe** [comment]
Well, currently, I always type it at the very top of the text area and leave it there for the entire session - the idea here was to make this more permanent since you are unlikely to rewrite an entire project to Swift in one session...

**Comment by drkameleon** [comment]
;)

**Comment by charlieMonroe** [comment]
An alternative would be to allow defining custom types in preferences. I.e. there would be a way to add "known classes and enums" in preferences...

**Comment by jrmgx** [comment]
I could not agree more, I spend a lot of time to put all my custom class and type on top of the file for the conversion to work. that's sad :(

**Comment by drkameleon** [comment]
> I could not agree more, I spend a lot of time to put all my custom class and type on top of the file for the conversion to work. that's sad :(

Jerome, I'm doing my best to get it ready for the next - 2.0 - big release. :)

**Comment by jrmgx** [comment]
thank you, you already did a great job.
Any idea when this release will be ready? Any beta channel?

**Comment by drkameleon** [comment]
> thank you, you already did a great job.

Thanks a lot! It's your feedback that makes the project move forward! ;-)

> Any idea when this release will be ready? 
I'm working hard to be able to release it tomorrow (by 3-4PM, GMT+1 Spanish Time ;-) )

> Any beta channel?
Well, not yet. And given that - in general (this time is rather an exception) - updates are rather fast, I'm not sure whether it's needed. But we'll see... :)

**Comment by drkameleon** [comment]
Feature implemented as of the upcoming 2.0 - looking forward to your feedback! :)

![screen shot 2015-10-31 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/1265028/10863311/378be0cc-7fc9-11e5-98ab-18397aba61bb.png)
