### ISSUE TITLE
Smarter String Interpolation

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#90]
It's really great now that `+[NSString stringWithFormat:]` uses Swift's string interpolation, however, it doesn't always work correctly.

Example:

```
NSDictionary *dict = ...;
NSString *str = [NSString stringWithFormat:@"123=%@", dict[@"my_key"]];
```

This gets translated by iSwift into:

```
let dict = ...
let str = "123=\(dict["my_key"])"
```

Unfortunately, since the expression itself includes quotes, this messes up the entire string. There are two ways to solve this:

```
let str = "123=" + dict["my_key"] + ""
let str = "123=" + dict["my_key"].description + ""
let str = String(format: "123=%@", dict["my_key"])
```

Generally when you detect that the expression contains quotes, you can split the string and insert the expression using + operator on each site. To be on the safe side, include `.description`, which is how the interpolation works anyways, but the code may look weird with strings... This particular example isn't going to work anyway, since `dict["my_key"]` returns an optional, but that's where the translation needs a human touch and I'm fine with it.

The third option is possible as well. Swift's `String` has an initializer that takes the exact same format string as `NSString` does. This should probably be done if you detect that the format string contains some formatting options that Swift's string interpolation cannot currently handle - e.g. `%0.2f` (floating number with 2 fraction digits), `%02i` (integer as two digits), etc.

**Comment by drkameleon** [comment]
Interesting catch - I'll see what can be done.

---

P.S. Development has been left a behind the last couple of days, since... all of the development team (me) has been down with the flu, but we'll be back soon! lol

**Comment by charlieMonroe** [comment]
No rush. Hope you get better soon!

**Comment by charlieMonroe** [comment]
Swift 2.1 (Xcode 7.1 released today), allows string literals in interpolations (http://www.russbishop.net/swift-2-1). So it no longer is such an issue, but IMHO having complex expressions as interpolations isn't pretty anyway...

**Comment by drkameleon** [comment]
Hmm... I see. So, I'm not sure whether it makes much sense.

Perhaps another Preference option? (but that would mean activating/deactivating string interpolation for the whole document -- we'll see...)
