### ISSUE TITLE
Basic Types Mapping

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#95]
Example:

```
-(NSUInteger)something {
    return 0;
}
```

Current result:

```
func something() -> NSUInteger {
	return 0
	
}
```

**Issue:** `NSUInteger` isn't a valid type in Swift. Here is some basic mapping that should be applied:

ObjC | Swift
------------ | -------------
`NSUInteger`|`UInt`
`NSInteger`|`Int`
`int`|`Int32`
`unsigned`|`UInt32`
`unsigned int`|`UInt32`

There's surely more, but can't think of any right now.

**Comment by drkameleon** [comment]
Hmm... I missed this one.

FYI, here's the table with all type conversions, so far:

```coffeescript
"NSString"              : "String"
"NSArray"               : "Array"
"NSDictionary"          : "Dictionary"
"NSInteger"             : "Int"
"bool"                  : "CBool"
"char"                  : "CChar"
"signed char"           : "CChar"
"unsigned char"         : "CUnsignedChar"
"short"                 : "CShort"
"signed short"			: "CShort"
"unsigned short"        : "CUnsignedShort"
"int"                   : "Int"
"signed int" 			: "CInt"
"unsigned int"          : "CUnsignedInt"
"long"                  : "CLong"
"signed long"			: "CLong"
"unsigned long"         : "CUnsignedLong"
"long long"             : "CLongLong"
"signed long long"		: "CLongLong"
"unsigned long long"    : "CUnsignedLongLong"
"wchar_t"               : "CWideChar"
"char16_t"              : "CChar16"
"char32_t"              : "CChar32"
"float"                 : "CFloat"
"double"                : "CDouble"
"id"                    : "AnyObject"
"BOOL"                  : "Bool"
"instancetype"			: "Self"
```

**Comment by charlieMonroe** [comment]
`"int"                   : "Int"`

In my source code (on OS X), Xcode converts this to `Int32`. It's possible it's new to Xcode 7, haven't tried it with 6.x. I.e. I have an ObjC class that returns `int` from one of the methods and the signature in Swift contains `Int32`...

**Comment by drkameleon** [comment]
Hmm... weird...

I've taken all of the above conversions from Apple's reference itself. :S Perhaps they changed it?!

I'll have to re-check this out.

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.0.

----

P.S. If you come across any official reference by Apple (regarding type conversions), please let me know - I don't think I can find it any more...

**Comment by charlieMonroe** [comment]
They change it every build :) E.g. Xcode 7.1 now properly returns `UInt` for `NSNumber`'s `unsigned...` properties. It returned `Int` before. Also many system frameworks use `Int` in Swift where `NSUInteger` was used. To be honest, it's a real mess.

**Comment by drkameleon** [comment]
Well... I know... lol.

I myself had spotted and consulted the above conversion table, and now I can hardly find where those `CInt` have gone... Rather messy, indeed.

**Comment by JanX2** [comment]
@charlieMonroe Replacing `NSUInteger` with `Int` is fine in places: CoreFoundation often uses `CFIndex` (signed) for values that are then exposed as `NSUInteger` by `Foundation`. So there is a great many places where this makes sense for a certain perspective. The argument for doing it this way used to be that values using `CFIndex` that cannot possible be negative should be exposed as `NSUInteger`…

**Comment by charlieMonroe** [comment]
@JanX2 - personally, I dislike this. For example `Array.count` - I don't see a reason why it should be a signed int - the whole purpose of unsigned integers is to use them where negative values make no sense (e.g. an array with negative number of items) - which also expands the possible value range...
