### ISSUE TITLE
Fix hex-decimal number conversion

### ISSUE THREAD

**Issue by charlieMonroe** [drkameleon/iswift#97]
This took me a while to track down :) Suddently stuff stopped working after conversion to Swift and here's the culprit:

```
int i = (seed * 0xd3 + 0x754f);
```

will become after iSwift:

```
let i = (seed*0xd3+0x754)
```

Notice the last number becoming `0x754` from `0x754f` - i.e. missing the trailing `f`.

**Comment by drkameleon** [comment]
Hmmm.... great catch this one. I'll fix it! ;-)

**Comment by drkameleon** [comment]
Question: Is the `f` part to be preserved in all cases? (hexadecimal numbers aside, I mean)

I don't think I have spotted a single instance of `0.123f` formmated number (`0.123` instead, sure) in all of Apple's reference...

**Comment by charlieMonroe** [comment]
Many people suffix floating point numbers with `f`.

But this should be applied only for hex-decimal numbers - i.e. numbers that start with `0x`...

**Comment by drkameleon** [comment]
Issue fixed as of the upcoming 2.0.
